### ISSUE TITLE
GenericDistribution fails with 4 arguments

### ISSUE THREAD

**Issue by jwharington** [SciML/SciMLExpectations.jl#76]
GenericDistribution constructor method fails when exactly 4 distribution arguments are supplied.

MWE example below:

```
using SciMLExpectations, Test
import Distributions

n=8
p_array=[Distributions.Uniform(0,1) for i in (1:n)]

@testset "Generic distribution, variable length" begin
	for i in (1:n)
		gd=GenericDistribution(p_array[1:i]...)
		@test all(isa.(rand(gd), Number))
	end
end
```

Failure (for i==4 here) occurs at rand(gd) call, with exception:

> MethodError: objects of type Distributions.Uniform{Float64} are not callable

**Comment by agerlach** [comment]
Thanks for reporting. It looks like the issue is that w/ 4 args it is using the default constructor vs the outer constructor. I will have to think of the best way to handle this.
