### ISSUE TITLE
Revive old tutorials

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLExpectations.jl#95]
https://docs.sciml.ai/SciMLTutorialsOutput/stable/DiffEqUncertainty/01-expectation_introduction/
https://docs.sciml.ai/SciMLTutorialsOutput/stable/DiffEqUncertainty/02-AD_and_optimization/

These need to be updated to SciMLExpectations

**Comment by ArnoStrouwen** [comment]
I think those are already here:
https://github.com/SciML/SciMLExpectations.jl/pull/92
